# Generated by Django 4.2.6 on 2023-10-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AddField(
            model_name='taller',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='talleres/'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/'),
        ),
    ]
