# Generated by Django 4.2.6 on 2023-11-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_foto_taller_foto_tecnico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='hora_apertura',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_cierre',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
