# Generated by Django 4.2.6 on 2023-11-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_taller_hora_apertura_taller_hora_cierre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='foto',
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
