# Generated by Django 4.2.6 on 2023-11-03 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='direccion',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='taller',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
