# Generated by Django 4.2.6 on 2023-11-04 19:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_taller_direccion_alter_taller_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
