# Generated by Django 4.2.6 on 2023-11-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_taller_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'cliente'), (3, 'taller'), (4, 'técnico')], default=1),
        ),
    ]
