# Generated by Django 4.2.6 on 2023-11-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'cliente'), (3, 'taller'), (4, 'tecnico')], default=1),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='especialidad',
            field=models.CharField(choices=[('mecanico_general', 'Mecánico General'), ('electrico', 'Eléctrico'), ('tornero', 'Tornero'), ('pintor', 'Pintor'), ('chapista', 'Chapista'), ('gomero', 'Gomero')], max_length=255),
        ),
    ]
