# Generated by Django 4.2.6 on 2023-11-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_taller_hora_apertura_taller_hora_cierre'),
        ('solicitudes_asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_estimado', models.CharField(help_text='Tiempo estimado para completar la asistencia.', max_length=50, verbose_name='Tiempo Estimado')),
                ('costo_estimado', models.DecimalField(decimal_places=2, help_text='Costo estimado para la asistencia.', max_digits=10, verbose_name='Costo Estimado')),
                ('estado_postulacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, verbose_name='Estado de la Postulación')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales sobre la postulación.', null=True, verbose_name='Comentarios')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='solicitudes_asistencia.solicitudasistencia')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.taller')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('estado_orden', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado de la Orden')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='solicitudes_asistencia.solicitudasistencia')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_asignadas', to='usuarios.tecnico')),
            ],
        ),
    ]
