# Generated by Django 4.2.6 on 2023-11-24 02:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_asistencia', '0004_alter_solicitudasistencia_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudasistencia',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
