# Generated by Django 4.2.6 on 2023-11-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_asistencia', '0006_alter_solicitudasistencia_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='distancia_estimada',
            field=models.CharField(default='1', help_text='Distancia Estimada para completar la asistencia.', max_length=50, verbose_name='Distancia Estimada'),
        ),
    ]
