"""
Django settings for mecanoMobile project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from firebase_admin import credentials, initialize_app
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# La ruta a tu archivo JSON
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'settings', 'mecanomobile-76f54-firebase-adminsdk-561m6-c571049b20.json')

# Inicializa la aplicación Firebase con tus credenciales
cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
initialize_app(cred)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-73#_5+irfo#x$%#6%3uzy13f)rps-)&hnp7z5z!law9(u82)kb'




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.gis',
    'fcm_django',
    'applications.usuarios',
    'applications.vehiculos',
    'applications.solicitudes_asistencia',


]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

FCM_DJANGO_SETTINGS = {
     "FCM_SERVER_KEY": "AAAAVbOT6vA:APA91bHwIouqe1Uy4h65udZqdOq3wDWRnDu_sUSPrukqicsVbVW4bj_J8L11sY1cKUdaFpBs1Wvv3n5FUN1eTrDZkegbSaETXxX8SKZm2HDRQCR8sAfQJaFXuvSao_6n3kzdmdt_hTo6"
}

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': "dkpuiyovk",
    'API_KEY': "469764952158318",
    'API_SECRET': "Za0rsohDusweXFfpyjCiFPUgzug",
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mecanoMobile.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mecanoMobile.wsgi.application'





# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GDAL_LIBRARY_PATH = 'C:\\Users\\aliss\\miniconda3\\Library\\bin\\gdal.dll'

AUTH_USER_MODEL = 'usuarios.Customuser'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),  # Hace que el Access Token dure 12 horas.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),  # Hace que el Refresh Token dure 14 días.
    # Puedes agregar otras configuraciones relacionadas a SIMPLE_JWT aquí si las necesitas.
}