# Generated by Django 4.2.6 on 2023-10-31 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_cliente_foto_taller_foto_tecnico_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('año', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='usuarios.cliente')),
            ],
        ),
    ]
